name: check Env
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2022
            cuda: "11.3.1"
            compiler: "Visual Studio 17 2022"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: check Env
        shell: pwsh
        run: |
          realpath -v
